name: Build and deploy ASP.Net Core app to Azure Web App - rahulwebapp0324

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build frontend
        run: |
          cd E-Commerce.Web
          # Replace the build command with the appropriate command for building your frontend code (e.g., npm run build for Node.js projects)
          npm install
          npm run build

      - name: Publish frontend artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: E-Commerce.Web/dist  # Adjust this path to the location of your frontend build artifacts

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: frontend
      
      - name: Deploy frontend to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rahulwebapp0324'
          slot-name: 'Production'
          # Specify the path to the frontend artifacts relative to the root of the repository
          package: ${{ github.workspace }}/frontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_00C732228880429181A163A02042655F }}
